TOPICS = [
    # Tech & Programming
    "python programming", "machine learning", "web development", "game design",
    "cryptography", "mechanical keyboards", "cybersecurity", "linux terminal shortcuts",
    "windows batch commands", "javascript", "html", "windows shortcut",
    "windows taskmgr functions", "ms-dos", "data science", "typescript",
    "rust programming", "docker containers", "kubernetes", "cloud computing",
    "api design", "database indexing", "regex patterns", "git version control",
    "vim editor", "bash scripting", "networking protocols", "tcp ip",
    "dns resolution", "oauth authentication", "websockets", "graphql",
    "microservices architecture", "devops pipelines", "unit testing",
    "assembly language", "c programming", "c++ programming", "java programming",
    "go programming", "swift programming", "kotlin programming", "r programming",
    "scala programming", "haskell programming", "erlang programming",
    "functional programming", "object oriented programming", "design patterns",
    "system design", "compiler design", "operating system internals",
    "memory management", "garbage collection", "multithreading", "concurrency",
    "distributed systems", "blockchain technology", "smart contracts",
    "web3 development", "solidity programming", "nft technology",
    "augmented reality development", "virtual reality development",
    "embedded systems programming", "firmware development", "iot programming",
    "arduino programming", "raspberry pi projects", "fpga programming",
    "reverse engineering", "binary exploitation", "malware analysis",
    "penetration testing", "ethical hacking", "sql injection",
    "buffer overflow attacks", "zero day vulnerabilities", "firewall configuration",
    "vpn technology", "tor network", "packet sniffing", "wireshark analysis",
    "rest api design", "grpc protocol", "message queues", "redis caching",
    "elasticsearch", "mongodb", "postgresql", "mysql optimization",
    "data warehousing", "etl pipelines", "apache spark", "hadoop ecosystem",
    "apache kafka", "data lakes", "feature engineering", "model deployment",
    "mlops", "neural networks", "deep learning", "convolutional neural networks",
    "recurrent neural networks", "transformer architecture", "large language models",
    "reinforcement learning", "generative adversarial networks", "diffusion models",
    "computer vision", "natural language processing", "speech recognition",
    "recommendation systems", "anomaly detection", "time series forecasting",
    "a b testing", "product analytics", "user experience design",
    "accessibility in web design", "responsive design", "progressive web apps",
    "react framework", "vue framework", "angular framework", "svelte framework",
    "nextjs framework", "nuxt framework", "django framework", "flask framework",
    "fastapi framework", "spring boot", "express nodejs", "deno runtime",
    "bun runtime", "webassembly", "threejs", "d3js data visualization",
    "tailwind css", "css animations", "sass preprocessing", "webpack bundling",
    "vite build tool", "ci cd pipelines", "github actions", "jenkins automation",
    "terraform infrastructure", "ansible automation", "pulumi cloud",
    "aws services", "google cloud platform", "azure cloud", "serverless computing",
    "edge computing", "cdn optimization", "load balancing", "reverse proxy",
    "nginx configuration", "apache server", "linux system administration",
    "shell scripting", "cron jobs", "systemd services", "docker compose",
    "helm charts", "service mesh", "observability", "prometheus monitoring",
    "grafana dashboards", "log aggregation", "distributed tracing",
    "chaos engineering", "site reliability engineering", "platform engineering",

    # Science & Physics
    "quantum physics", "climate science", "black hole thermodynamics",
    "orbital mechanics", "numerical integration methods", "classical mechanics",
    "probability cloud", "aerodynamics", "marine biology", "astronomy",
    "thermodynamics", "electromagnetism", "fluid dynamics", "particle physics",
    "string theory", "relativity", "dark matter", "nuclear fusion",
    "evolutionary biology", "genetics", "neuroscience", "biochemistry",
    "plate tectonics", "atmospheric chemistry", "quantum entanglement",
    "quantum computing", "quantum cryptography", "quantum field theory",
    "loop quantum gravity", "multiverse theory", "simulation hypothesis",
    "fermi paradox", "drake equation", "dark energy", "cosmic microwave background",
    "neutron stars", "pulsars", "magnetars", "quasars", "gamma ray bursts",
    "gravitational waves", "ligo detector", "event horizon telescope",
    "james webb telescope discoveries", "hubble constant tension",
    "stellar nucleosynthesis", "big bang theory", "cosmic inflation",
    "solar physics", "heliosphere", "coronal mass ejections",
    "aurora borealis", "magnetosphere", "van allen belts",
    "exoplanet detection", "habitable zones", "astrobiology",
    "space propulsion systems", "ion drives", "nuclear propulsion",
    "solar sails", "space elevator concept", "dyson sphere concept",
    "terraforming mars", "lunar colonization", "asteroid mining",
    "crispr gene editing", "stem cell research", "epigenetics",
    "proteomics", "metabolomics", "systems biology", "synthetic biology",
    "bioinformatics", "computational biology", "structural biology",
    "virology", "immunology", "pharmacology", "toxicology",
    "cancer biology", "aging science", "longevity research",
    "microbiome science", "gut brain axis", "chronobiology",
    "bioluminescence", "biomimicry", "extremophiles",
    "deep sea biology", "coral reef ecology", "wetland ecology",
    "wildlife conservation", "rewilding", "invasive species",
    "soil science", "mycology", "ethnobotany", "dendrochronology",
    "glaciology", "oceanography", "limnology", "volcanology",
    "seismology", "geochemistry", "mineralogy", "paleontology",
    "paleoanthropology", "astrogeology", "space weather",

    # Mathematics
    "integration", "derivatives", "quadratic formula", "cubic formula",
    "quartic formula", "vector", "vector field", "scalars", "linear algebra",
    "differential equations", "fourier transforms", "number theory",
    "graph theory", "set theory", "topology", "bayesian statistics",
    "complex numbers", "matrix operations", "probability distributions",
    "calculus of variations", "abstract algebra", "combinatorics",
    "real analysis", "complex analysis", "functional analysis",
    "harmonic analysis", "numerical analysis", "stochastic processes",
    "markov chains", "monte carlo methods", "game theory",
    "information theory", "coding theory", "cryptographic mathematics",
    "elliptic curve cryptography", "modular arithmetic",
    "prime number theory", "riemann hypothesis", "p vs np problem",
    "chaos theory", "fractal geometry", "mandelbrot set",
    "knot theory", "algebraic geometry", "differential geometry",
    "tensor calculus", "lie groups", "category theory",
    "mathematical logic", "proof theory", "model theory",
    "boolean algebra", "lambda calculus", "turing machines",
    "automata theory", "formal languages", "computational complexity",
    "optimization algorithms", "linear programming", "convex optimization",
    "dynamic programming", "greedy algorithms", "divide and conquer",
    "sorting algorithms", "searching algorithms", "hash functions",
    "tree data structures", "graph algorithms", "pathfinding algorithms",
    "compression algorithms", "encryption algorithms", "hashing algorithms",

    # Renewable Energy & Environment
    "renewable energy", "solar panel efficiency", "wind turbine design",
    "hydroelectric power", "geothermal energy", "carbon capture",
    "electric vehicle batteries", "smart grid technology",
    "tidal energy", "wave energy", "biomass energy", "biogas production",
    "hydrogen fuel cells", "solid state batteries", "supercapacitors",
    "energy storage systems", "grid scale batteries", "pumped hydro storage",
    "compressed air energy storage", "flywheel energy storage",
    "perovskite solar cells", "thin film solar", "concentrated solar power",
    "offshore wind farms", "vertical axis wind turbines",
    "nuclear energy safety", "thorium reactors", "molten salt reactors",
    "fusion energy progress", "iter project", "tokamak reactors",
    "carbon trading markets", "green hydrogen", "sustainable aviation fuel",
    "circular economy", "zero waste lifestyle", "lifecycle assessment",
    "environmental impact assessment", "ecological footprint",
    "deforestation causes", "ocean acidification", "permafrost thawing",
    "methane emissions", "ozone layer recovery", "acid rain",
    "microplastics pollution", "light pollution", "noise pollution",
    "sustainable agriculture", "vertical farming", "aquaponics",
    "regenerative farming", "precision agriculture", "food waste reduction",
    "water scarcity solutions", "desalination technology", "rainwater harvesting",
    "constructed wetlands", "green roofs", "urban heat islands",
    "passive house design", "net zero buildings", "green architecture",

    # Arts, Culture & History
    "sourdough baking", "ancient history", "renaissance art",
    "origami folding techniques", "acoustic guitar chords",
    "world history timelines", "world war", "financial literacy",
    "video editing bitrates", "calisthenics", "oil painting techniques",
    "watercolor painting", "jazz music theory", "classical composition",
    "film cinematography", "typography design", "3d sculpting",
    "leather crafting", "pottery wheel techniques", "calligraphy",
    "mythology", "medieval warfare", "ancient civilizations",
    "the cold war", "the industrial revolution", "colonialism",
    "the roman empire", "ancient egypt", "the silk road",
    "byzantine empire", "ottoman empire", "mongol empire",
    "aztec civilization", "mayan civilization", "inca empire",
    "ancient greece", "ancient mesopotamia", "ancient india",
    "ancient china", "feudal japan", "viking age",
    "age of exploration", "french revolution", "american revolution",
    "russian revolution", "chinese revolution", "decolonization movements",
    "civil rights movement", "suffragette movement", "labor movement",
    "philosophy of stoicism", "existentialism", "nihilism",
    "utilitarianism", "kantian ethics", "virtue ethics",
    "eastern philosophy", "buddhist philosophy", "confucianism",
    "taoism", "zen philosophy", "socratic method",
    "ancient greek drama", "shakespearean literature", "romantic poetry",
    "modernist literature", "postmodern fiction", "magical realism",
    "gothic literature", "noir fiction", "science fiction history",
    "fantasy world building", "comic book history", "manga culture",
    "anime production", "film noir history", "new wave cinema",
    "documentary filmmaking", "screenwriting structure", "game narrative design",
    "impressionism art movement", "cubism", "surrealism", "abstract expressionism",
    "pop art", "street art", "digital art", "concept art",
    "graphic design principles", "logo design", "brand identity",
    "user interface design", "motion graphics", "3d rendering",
    "music production", "electronic music synthesis", "hip hop production",
    "music theory fundamentals", "chord progressions", "music mixing",
    "music mastering", "sound design", "foley art",
    "ballet technique", "contemporary dance", "breakdancing",
    "traditional folk dances", "acting techniques", "stage combat",
    "voice acting", "improv comedy", "stand up comedy structure",
    "fashion history", "textile design", "jewelry making",
    "sculpture techniques", "printmaking", "photography composition",
    "darkroom photography", "street photography", "portrait lighting",
    "food photography", "architectural photography", "astrophotography",

    # Lifestyle & Practical Skills
    "personal finance", "stock market investing", "real estate basics",
    "time management", "speed reading", "memory techniques",
    "public speaking", "negotiation skills", "minimalism",
    "meditation practices", "sleep optimization", "nutrition science",
    "home brewing", "urban gardening", "woodworking joints",
    "home electrical wiring", "plumbing basics", "car maintenance",
    "wilderness survival", "first aid", "knot tying",
    "index fund investing", "options trading", "cryptocurrency investing",
    "tax optimization strategies", "retirement planning", "budgeting methods",
    "debt management", "credit score improvement", "estate planning",
    "insurance basics", "health insurance navigation", "mortgage basics",
    "frugal living", "passive income streams", "freelancing finances",
    "entrepreneurship basics", "business plan writing", "startup funding",
    "venture capital", "angel investing", "crowdfunding campaigns",
    "dropshipping business", "print on demand", "affiliate marketing",
    "content creation monetization", "youtube growth strategies",
    "podcast production", "newsletter writing", "copywriting",
    "seo optimization", "social media marketing", "email marketing",
    "project management methodologies", "agile scrum", "kanban method",
    "pomodoro technique", "deep work strategies", "habit formation",
    "journaling techniques", "gratitude practice", "mindfulness",
    "cognitive behavioral therapy basics", "stoic daily practices",
    "intermittent fasting", "ketogenic diet", "plant based nutrition",
    "macro tracking", "sports nutrition", "supplement science",
    "strength training programming", "powerlifting", "olympic weightlifting",
    "crossfit methodology", "yoga styles", "pilates method",
    "rock climbing techniques", "parkour basics", "martial arts",
    "brazilian jiu jitsu", "boxing footwork", "kettlebell training",
    "running form", "marathon training", "triathlon preparation",
    "swimming techniques", "cycling training", "rowing technique",
    "foam rolling", "mobility training", "injury prevention",
    "cold exposure therapy", "breathwork techniques", "sauna benefits",
    "foraging wild plants", "mushroom hunting", "bushcraft skills",
    "fire starting methods", "shelter building", "water purification",
    "navigation without gps", "amateur radio", "ham radio licensing",
    "morse code", "lock picking", "lock smithing",
    "home security systems", "self defense basics", "situational awareness",
    "emergency preparedness", "disaster planning", "food preservation",
    "canning and pickling", "fermentation basics", "cheese making",
    "bread baking science", "pasta making", "knife sharpening",
    "butchery basics", "sushi preparation", "french cooking techniques",
    "spice blending", "cocktail mixology", "wine tasting", "coffee brewing",
    "tea ceremony", "cigar rolling", "candle making", "soap making",
    "beekeeping", "chicken keeping", "goat farming", "composting",
    "hydroponics", "permaculture design", "seed saving",
    "bicycle repair", "motorcycle maintenance", "boat maintenance",
    "welding basics", "metalworking", "blacksmithing",
    "glass blowing", "stone carving", "bookbinding",
    "watchmaking", "electronics repair", "soldering basics",
    "pcb design", "3d printing", "laser cutting", "cnc machining",
    "sewing and tailoring", "quilting", "embroidery", "knitting",
    "crocheting", "macrame", "weaving", "basket making",
    "fly fishing", "ice fishing", "spear fishing",
    "bow hunting", "falconry", "dog training",
    "horse riding", "bird watching", "insect collecting",
    "astronomy stargazing", "meteor shower watching", "telescope operation",
    "chess strategy", "go game strategy", "bridge card game",
    "poker strategy", "speed cubing", "competitive puzzling",
    "language learning strategies", "polyglot methods",
    "sign language", "braille reading", "speed typing",
    "touch typing", "shorthand writing", "stenography",

    # Health & Medicine
    "anatomy basics", "physiology fundamentals", "pathophysiology",
    "pharmacokinetics", "drug interactions", "vaccine science",
    "epidemiology basics", "biostatistics", "clinical trials",
    "evidence based medicine", "diagnostic reasoning", "triage methods",
    "cpr techniques", "wound care", "fracture management",
    "emergency medicine", "trauma care", "palliative care",
    "mental health awareness", "anxiety management", "depression treatment",
    "adhd management", "autism spectrum understanding", "ptsd treatment",
    "addiction recovery", "eating disorder recovery", "grief processing",
    "therapy modalities", "psychotherapy approaches", "psychiatry basics",
    "neurofeedback", "biofeedback therapy", "emdr therapy",
    "sleep disorders", "circadian rhythm", "chronotherapy",
    "pain management", "chronic illness management", "autoimmune diseases",
    "gut health optimization", "liver detoxification", "kidney health",
    "heart health", "blood pressure management", "cholesterol management",
    "diabetes management", "thyroid health", "hormonal balance",
    "womens health", "mens health", "pediatric health",
    "geriatric care", "preventive medicine", "longevity practices",
    "traditional chinese medicine", "ayurvedic medicine", "herbal medicine",
    "acupuncture science", "chiropractic care", "physical therapy",
    "occupational therapy", "speech therapy", "vision therapy",

    # Social Sciences & Humanities
    "sociology fundamentals", "social psychology", "behavioral economics",
    "cognitive psychology", "developmental psychology", "evolutionary psychology",
    "personality psychology", "positive psychology", "forensic psychology",
    "anthropology basics", "cultural anthropology", "forensic anthropology",
    "political science", "international relations", "geopolitics",
    "diplomacy and negotiation", "propaganda analysis", "media literacy",
    "misinformation detection", "critical thinking", "logical fallacies",
    "rhetoric and persuasion", "debate techniques", "argumentation theory",
    "economics fundamentals", "macroeconomics", "microeconomics",
    "behavioral finance", "market psychology", "supply chain economics",
    "labor economics", "environmental economics", "development economics",
    "sociology of religion", "comparative religion", "mythology origins",
    "linguistics fundamentals", "etymology", "semantics", "syntax",
    "phonetics", "sociolinguistics", "psycholinguistics",
    "archaeology methods", "numismatics", "genealogy research",
    "archival research", "oral history", "historiography",
    "urban planning", "city design", "transportation planning",
    "law fundamentals", "contract law", "intellectual property law",
    "criminal law", "constitutional law", "international law",
    "legal reasoning", "court procedures", "legal writing",
]

TEMPLATES = [
    # Learning & Understanding
    "how to learn about {topic}",
    "efficient methods for understanding {topic}",
    "what is {topic}",
    "how can i learn {topic}",
    "explain {topic} to a child",
    "explain {topic} to a complete beginner",
    "explain {topic} like i am five",
    "explain {topic} like i am an expert",
    "explain {topic} using an analogy",
    "explain {topic} using a real life example",
    "explain {topic} in simple terms",
    "explain {topic} in one sentence",
    "explain {topic} in one paragraph",
    "eli5 {topic}",
    "best {topic} tutorials for beginners",
    "easiest tutorials for people who just started {topic}",
    "free resources to learn {topic}",
    "best books to learn {topic}",
    "best youtube channels for learning {topic}",
    "best online courses for {topic}",
    "best podcasts about {topic}",
    "best documentaries about {topic}",
    "best websites for learning {topic}",
    "best reddit communities for {topic}",
    "best discord servers for {topic}",
    "how long does it take to learn {topic}",
    "can i self-teach {topic}",
    "roadmap for learning {topic} from scratch",
    "prerequisites for learning {topic}",
    "what should i know before studying {topic}",
    "how to go from zero to expert in {topic}",
    "how to study {topic} effectively",
    "how to stay motivated while learning {topic}",
    "how to practice {topic} every day",
    "how to track your progress in {topic}",
    "how to test yourself on {topic}",
    "flashcard strategies for memorizing {topic}",
    "spaced repetition techniques for {topic}",
    "how to take notes on {topic}",
    "mind mapping for {topic}",
    "feynman technique applied to {topic}",
    "pomodoro technique for studying {topic}",
    "active recall methods for {topic}",
    "how to avoid burnout while learning {topic}",
    "learning {topic} as an adult",
    "learning {topic} with no prior experience",
    "is it too late to learn {topic} at {age}",
    "learning {topic} in {duration} days",
    "can you become proficient in {topic} in a month",
    "30 day challenge for learning {topic}",
    "one week crash course for {topic}",
    "100 days of {topic} challenge",

    # History & Background
    "history of {topic}",
    "the history behind {topic}",
    "who invented {topic}",
    "who discovered {topic}",
    "where did {topic} originate",
    "how has {topic} evolved over time",
    "the future of {topic}",
    "milestones in the development of {topic}",
    "famous pioneers of {topic}",
    "timeline of {topic} development",
    "key events in the history of {topic}",
    "how {topic} has changed over the last decade",
    "how {topic} has changed over the last century",
    "the golden age of {topic}",
    "the decline and resurgence of {topic}",
    "controversial moments in the history of {topic}",
    "how {topic} was discovered by accident",
    "unsolved mysteries in {topic}",
    "forgotten figures who shaped {topic}",
    "how war influenced the development of {topic}",
    "how politics shaped {topic}",
    "cultural influences on {topic}",
    "the economics behind {topic}",
    "philosophy behind {topic}",

    # How It Works
    "how does {topic} work",
    "how do things work in {topic}",
    "the science behind {topic}",
    "step by step explanation of {topic}",
    "real world examples of {topic}",
    "how is {topic} used in everyday life",
    "what problems does {topic} solve",
    "applications of {topic} in industry",
    "how does {topic} work under the hood",
    "the mechanics of {topic} explained",
    "the math behind {topic}",
    "the physics behind {topic}",
    "the chemistry behind {topic}",
    "the biology behind {topic}",
    "the engineering behind {topic}",
    "how {topic} is made",
    "how {topic} is designed",
    "how {topic} is built from scratch",
    "how {topic} scales to millions of users",
    "how {topic} handles edge cases",
    "how {topic} fails and what happens when it does",
    "how {topic} is tested",
    "how {topic} is optimized for performance",
    "what happens inside {topic} at the hardware level",
    "visualizing how {topic} works",
    "intuitive explanation of {topic}",
    "mental models for understanding {topic}",
    "analogies to understand {topic}",
    "thought experiments related to {topic}",

    # Trends & Importance
    "latest trends in {topic}",
    "why is {topic} important",
    "the significance of {topic} in society",
    "why is {topic} growing in popularity",
    "how is {topic} changing the world",
    "the impact of {topic} on modern life",
    "why every professional should understand {topic}",
    "future career opportunities in {topic}",
    "why {topic} matters in {year}",
    "is {topic} still relevant in {year}",
    "the rise of {topic} explained",
    "why {topic} is the next big thing",
    "how {topic} is disrupting industries",
    "what industries are being transformed by {topic}",
    "how {topic} is affecting the job market",
    "what governments are doing about {topic}",
    "ethical implications of {topic}",
    "environmental impact of {topic}",
    "social consequences of {topic}",
    "economic ripple effects of {topic}",
    "how {topic} affects mental health",
    "how {topic} is used in education",
    "how {topic} is used in healthcare",
    "how {topic} is used in finance",
    "how {topic} is used in entertainment",
    "how {topic} is used in military",
    "how {topic} is used in space exploration",
    "how {topic} is used in art",
    "how {topic} is used in sports",
    "how {topic} affects privacy",
    "how {topic} affects democracy",
    "how {topic} affects inequality",

    # Difficulty & Obstacles
    "why is {topic} difficult to learn",
    "common obstacles in mastering {topic}",
    "why do beginners struggle with {topic}",
    "the hardest parts of {topic} explained",
    "how to overcome challenges in {topic}",
    "is {topic} worth learning in {year}",
    "is {topic} harder than {alternative}",
    "how steep is the learning curve for {topic}",
    "what makes {topic} so intimidating",
    "how to push through plateaus in {topic}",
    "how to deal with imposter syndrome in {topic}",
    "why most people give up on {topic}",
    "what nobody tells you about learning {topic}",
    "brutal truths about learning {topic}",
    "honest review of learning {topic}",
    "what i wish i knew before starting {topic}",
    "things that surprised me about {topic}",
    "what beginners always get wrong about {topic}",
    "misconceptions that slow down learning in {topic}",

    # Facts & Trivia
    "top 10 facts about {topic}",
    "popular facts about {topic}",
    "surprising things most people dont know about {topic}",
    "common myths about {topic} debunked",
    "fun facts about {topic}",
    "mind blowing facts about {topic}",
    "counterintuitive facts about {topic}",
    "weird edge cases in {topic}",
    "paradoxes in {topic}",
    "famous unsolved problems in {topic}",
    "greatest achievements in {topic}",
    "world records related to {topic}",
    "famous failures in {topic} and what we learned",
    "the most dangerous aspects of {topic}",
    "the most beautiful concepts in {topic}",
    "the most controversial topics within {topic}",
    "things that seem obvious about {topic} but arent",
    "things that are commonly confused in {topic}",
    "little known facts about {topic}",
    "the darkest side of {topic}",
    "trivia questions about {topic}",
    "quiz questions on {topic}",

    # Comparison
    "{topic} vs {alternative}",
    "what is the difference between {topic} and {alternative}",
    "which is better {topic} or {alternative}",
    "{topic} and {alternative} compared",
    "when to use {topic} instead of {alternative}",
    "pros and cons of {topic} vs {alternative}",
    "similarities between {topic} and {alternative}",
    "{topic} vs {alternative} for beginners",
    "{topic} vs {alternative} for professionals",
    "{topic} vs {alternative} in {year}",
    "why i switched from {alternative} to {topic}",
    "why i switched from {topic} to {alternative}",
    "can {topic} replace {alternative}",
    "is {topic} better than {alternative}",
    "combining {topic} with {alternative}",
    "how {topic} complements {alternative}",
    "the relationship between {topic} and {alternative}",
    "understanding both {topic} and {alternative}",
    "using {topic} alongside {alternative}",

    # Mistakes & Best Practices
    "common mistakes in {topic}",
    "mistakes made by beginners in {topic}",
    "what not to do when learning {topic}",
    "bad habits to avoid in {topic}",
    "best practices for {topic}",
    "tips for mastering {topic}",
    "how to get better at {topic} faster",
    "simple guide to {topic}",
    "cheat sheet for {topic}",
    "quick reference guide for {topic}",
    "antipatterns in {topic}",
    "code smells in {topic}",
    "pitfalls of {topic} in production",
    "security mistakes in {topic}",
    "performance pitfalls in {topic}",
    "mistakes that cost companies millions in {topic}",
    "lessons learned the hard way in {topic}",
    "how experts think about {topic} differently",
    "what separates amateurs from professionals in {topic}",
    "habits of highly effective people in {topic}",
    "daily routines of {topic} experts",
    "how masters of {topic} approach problems",

    # Projects & Practice
    "beginner projects to practice {topic}",
    "intermediate projects for {topic}",
    "advanced projects for {topic}",
    "how to build a portfolio in {topic}",
    "hands on ways to practice {topic}",
    "exercises to improve at {topic}",
    "fun side projects for {topic}",
    "real world problems to solve with {topic}",
    "hackathon ideas for {topic}",
    "open source projects to contribute to in {topic}",
    "step by step project tutorial for {topic}",
    "capstone project ideas for {topic}",
    "portfolio worthy projects in {topic}",
    "how to document your {topic} projects",
    "how to present a {topic} project in an interview",
    "how to write case studies for your {topic} work",
    "impressive things you can build with {topic}",
    "what can you create after learning {topic}",

    # Career & Professional
    "jobs that require knowledge of {topic}",
    "how to get a job in {topic}",
    "certifications worth getting in {topic}",
    "how to put {topic} on a resume",
    "salary expectations for {topic} professionals",
    "how to break into {topic} with no experience",
    "interview questions for {topic}",
    "how to ace a {topic} technical interview",
    "freelance opportunities in {topic}",
    "remote jobs in {topic}",
    "highest paying careers in {topic}",
    "underrated career paths in {topic}",
    "how to transition into {topic} from another field",
    "networking tips for people in {topic}",
    "how to find a mentor in {topic}",
    "how to build your personal brand in {topic}",
    "conferences and events for {topic} professionals",
    "speaking opportunities in {topic}",
    "how to write about {topic} professionally",
    "how to teach {topic} to others",
    "how to build a course on {topic}",
    "thought leaders to follow in {topic}",
    "companies that specialize in {topic}",
    "startups disrupting the {topic} space",

    # Tools & Resources
    "best tools for {topic}",
    "software used in {topic}",
    "open source projects related to {topic}",
    "communities and forums for {topic} enthusiasts",
    "newsletters about {topic} worth subscribing to",
    "free tools for {topic}",
    "paid tools worth the money for {topic}",
    "browser extensions for {topic}",
    "mobile apps for learning {topic}",
    "desktop apps for {topic}",
    "command line tools for {topic}",
    "libraries and frameworks for {topic}",
    "apis related to {topic}",
    "datasets for practicing {topic}",
    "sandboxes and playgrounds for {topic}",
    "simulators for {topic}",
    "hardware tools for {topic}",
    "lab setup for {topic}",
    "how to set up your environment for {topic}",
    "productivity tools for {topic} professionals",
    "automation tools for {topic}",
    "ai tools for {topic}",
    "how ai is changing {topic}",

    # Opinion & Debate
    "is {topic} overhyped",
    "is {topic} underrated",
    "unpopular opinions about {topic}",
    "controversial takes on {topic}",
    "hot takes on {topic}",
    "is {topic} dying",
    "is {topic} the future",
    "will {topic} ever be solved",
    "will {topic} replace {alternative}",
    "the biggest debate in {topic} right now",
    "people who hate {topic} and why",
    "critics of {topic} and their arguments",
    "defenders of {topic} and their reasoning",
    "the case for {topic}",
    "the case against {topic}",
    "why some experts disagree about {topic}",
    "what the mainstream gets wrong about {topic}",
    "what contrarians say about {topic}",
    "how public perception of {topic} has shifted",
    "why {topic} gets so much criticism",
    "why {topic} has such a passionate fanbase",
    "the toxicity in {topic} communities",
    "gatekeeping in {topic} culture",

    # Storytelling & Narrative
    "a day in the life of someone who works in {topic}",
    "my journey learning {topic}",
    "how {topic} changed my life",
    "the moment i fell in love with {topic}",
    "the hardest lesson i learned from {topic}",
    "failure stories from {topic} that led to success",
    "how i went from beginner to expert in {topic}",
    "interview with a professional in {topic}",
    "what it feels like to master {topic}",
    "personal essay on why {topic} matters to me",
    "letter to my past self about learning {topic}",
    "advice i would give my younger self about {topic}",

    # Age & Audience Specific
    "teaching {topic} to kids",
    "how to make {topic} fun for children",
    "{topic} for teenagers",
    "{topic} for seniors",
    "{topic} for people with disabilities",
    "accessibility in {topic}",
    "{topic} for non technical people",
    "{topic} for artists",
    "{topic} for entrepreneurs",
    "{topic} for teachers",
    "{topic} for doctors",
    "{topic} for lawyers",
    "{topic} for scientists",
    "{topic} for athletes",
    "{topic} for writers",
    "{topic} for parents",

    # Productivity & Workflow
    "how to automate tasks in {topic}",
    "workflow optimization for {topic}",
    "how professionals organize their {topic} work",
    "templates and frameworks for {topic}",
    "how to batch similar tasks in {topic}",
    "how to review and refine your {topic} work",
    "how to give and receive feedback in {topic}",
    "how to collaborate with others on {topic}",
    "pair programming equivalent in {topic}",
    "code review culture in {topic}",
    "how to write documentation for {topic}",
    "how to present {topic} to non experts",
    "how to explain {topic} in a job interview",
    "how to write a {topic} specification",
    "how to estimate time for {topic} projects",
]

ADJACENT_KEYS = {
    'a': 'sqwz', 'b': 'vghn', 'c': 'xdfv', 'd': 'srfce', 'e': 'wrsdf',
    'f': 'drtgv', 'g': 'ftyhb', 'h': 'gyujn', 'i': 'ujko', 'j': 'huikm',
    'k': 'jiol', 'l': 'kop', 'm': 'njk', 'n': 'bhjm', 'o': 'iklp',
    'p': 'ol', 'q': 'wa', 'r': 'edft', 's': 'awedxz', 't': 'rfgy',
    'u': 'yhji', 'v': 'cfgb', 'w': 'qase', 'x': 'zsdc', 'y': 'tghu',
    'z': 'asx', ' ': ' '
}
